language: cpp
dist: xenial

cache:
  directories:
    - $HOME/.ccache
    - $HOME/deps

addons:
  apt:
    update: true
    sources: &default_sources
      - ubuntu-toolchain-r-test
      - boost-latest
    packages: &default_packages
      # - libhdf5-dev
      - doxygen
      - graphviz

matrix:
  include:

    - os: linux
      compiler: gcc
      env: MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && MAKE_TEST=true"
      addons: {apt: { packages: [*default_packages, g++-7], sources: [*default_sources]}}

    - os: linux
      compiler: gcc
      env: MATRIX_EVAL="CC=gcc-8 && CXX=g++-8 && TRAVIS_BUILD_DOCS=true"
      addons: {apt: { packages: [*default_packages, g++-8], sources: [*default_sources]}}

    - os: linux
      compiler: clang
      env: MATRIX_EVAL="CC=clang && CXX=clang++ && MAKE_TEST=true"
      addons: {apt: { packages: [*default_packages], sources: [*default_sources]}}

    #- os: osx
    #  osx_image: xcode10.1
    #  compiler: clang
    #  env: MATRIX_EVAL="CXX_ID=clang7 && CC=clang && CXX=clang++ && MAKE_TEST=true"

    #- os: osx
    #  osx_image: xcode10.1
    #  compiler: clang
    #  env: MATRIX_EVAL="CXX_ID=apple && CC=cc && CXX=c++"

before_install:
  - eval "${MATRIX_EVAL}"
  # OpenMP issue with linux+clang
  #- export LD_LIBRARY_PATH=/usr/local/clang/lib:$LD_LIBRARY_PATH
  # Check commit matches expected commit (because of Travis bug)
  - |
    if [[ "$TRAVIS_COMMIT" != "$(git rev-parse HEAD)" ]]; then
      echo "Commit doesn't match expected $TRAVIS_COMMIT";
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$CXX_ID" == "clang6" ]]; then
      brew install llvm@6 libomp
      # brew link --force --overwrite llvm@6
      export PATH="$(brew --prefix llvm@6)/bin:$PATH"
      ls
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$CXX_ID" == "clang7" ]]; then
      brew install llvm@7 libomp
      # brew link --force --overwrite llvm@7
      export PATH="$(brew --prefix llvm@7)/bin:$PATH"
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$CXX_ID" == "gcc" ]]; then
      brew install gcc
      export PATH="/usr/local/bin:$PATH"
      export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
      export STRIDE_FORCE_NO_PROTOC=ON
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$CC" == "clang" ]]; then
      export LD_LIBRARY_PATH="/usr/local/clang/lib:$LD_LIBRARY_PATH"
    fi

install:
    #--------- All platforms
  - |
    #           STRIDE_FORCE_NO_BOOST: do not use bjam to build boost (mac+gcc problems)
    #			STRIDE_BOOST_ROOT: specify where the correct version of boost can be found
    #			STRIDE_BOOST_NO_SYSTEM_PATHS: should be ON to prevent mixing different versions of boost
    if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$CXX_ID" == "gcc" ]]; then
      export STRIDE_FORCE_NO_BOOST=ON
      export STRIDE_BOOST_NO_SYSTEM_PATHS=ON
    else
      export BOOST_ROOT=$HOME/deps/boost_1_69_0
      if [[ -z "$(ls -A $BOOST_ROOT)" ]]; then
        cd /tmp/
        wget https://dl.bintray.com/boostorg/release/1.69.0/source/boost_1_69_0.tar.gz -q
        tar xf boost_1_69_0.tar.gz > /dev/null 2>&1
        cd boost_1_69_0/
        ./bootstrap.sh --prefix=$BOOST_ROOT --with-libraries=chrono,date_time,filesystem,iostreams,locale,regex,system,thread
        ./b2 -q -a -j2 -d0 --disable-filesystem2 cxxflags="-v -std=c++11" threading=multi install
        cd $TRAVIS_BUILD_DIR;
      else
        echo "Already have boost cache"
      fi
      export LD_LIBRARY_PATH=$BOOST_ROOT/lib:$LD_LIBRARY_PATH
      sudo rm -f /usr/local/lib/libboost*.dylib*
      sudo ln -s $BOOST_ROOT/lib/*.{so,dylib}* /usr/local/lib
    fi

script:
  - make all && if [[ "$MAKE_TEST" = "true" ]]; then make test; fi

after_success:
    # Generate the docs only if master, the travis_build_docs is true and we can use secure variables
  - |
    if [[ "$TRAVIS_BRANCH" = "master" && "$TRAVIS_BUILD_DOCS" = "true" && "$TRAVIS_PULL_REQUEST" = "false" ]]; then
      cd $TRAVIS_BUILD_DIR
      chmod +x resources/sh/generate-doxygen.sh
      resources/sh/generate-doxygen.sh
    fi
