#!/bin/bash
#set -x

#====================================================================================================
# Utility functions:
# see https://stackoverflow.com/questions/4438306/how-to-remove-trailing-whitespaces-with-sed/4438318
#====================================================================================================

function trim_trailing_space() {
  if [[ $# -eq 0 ]]; then
    echo "$FUNCNAME will trim (in place) trailing spaces in the given file (remove unwanted spaces at end of lines)"
    echo "Usage :"
    echo "$FUNCNAME file"
    return
  fi
  local file=$1
  unamestr=$(uname)
  if [[ $unamestr == 'Darwin' ]]; then
    #specific case for Mac OSX
    sed -E -i ''  's/[[:space:]]*$//' $file
  else
    sed -i  's/[[:space:]]*$//' $file
  fi
}

function find_source_files() {
  if [[ $# -eq 0 ]]; then
    echo "$FUNCNAME will list sources files (having extensions $SRC_FILES_EXTENSIONS)"
    echo "Usage :"
    echo "$FUNCNAME folder"
    return
  fi
  local folder=$1

  unamestr=$(uname)
  if [[ $unamestr == 'Darwin' ]]; then
    #specific case for Mac OSX
    find -E $folder -iregex '.*\.('$SRC_FILES_EXTENSIONS')'
  else
    #Rhahhh, lovely
    local extensions_escaped=$(echo $SRC_FILES_EXTENSIONS | sed s/\|/\\\\\|/g)
    #echo "extensions_escaped:$extensions_escaped"
    find $folder -iregex '.*\.\('$extensions_escaped'\)$'
  fi
}

function trim_trailing_space_all_source_files() {
    local folder=$1
    for f in $(find_source_files $folder); do trim_trailing_space $f;done
}

#====================================================================================================
# Do the source files in main/cpp and test/cpp and main/python
# Pyhons folks seem somewhat divided on "blanks" but the top answer in
# https://stackoverflow.com/questions/2727988/python-indentation-in-empty-lines
# clinches it for me.
#====================================================================================================

SRC_FILES_EXTENSIONS="cpp|h|hpp|py"

for d in main/cpp test/cpp main/python test/python
do
    trim_trailing_space_all_source_files $d
    find $d -name "CMakeLists.txt" -type f -exec sed -E -i '' 's/[[:space:]]*$//' {} \; -exec echo {} \;
done

if [[ $(uname) == 'Darwin' ]]; then
    find . -maxdepth 1 \( -name "*.txt" -o -name "*.cmake" -o -name "Makefile" \) -type f \
        -exec sed -E -i ''  's/[[:space:]]*$//' {} \; -exec echo {} \;
else
    find . -maxdepth 1 \( -name "*.txt" -o -name "*.cmake" -o -name "Makefile" \) -type f \
        -exec sed -i  's/[[:space:]]*$//' {} \; -exec echo {} \;
fi

#====================================================================================================
